# Generated by Django 5.1.4 on 2024-12-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales', 'Sales'), ('viewer', 'Viewer'), ('customer', 'Customer'), ('bot', 'Bot')], default='viewer', max_length=20),
        ),
    ]
