# Generated by Django 5.1.4 on 2024-12-05 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_options'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='company',
            field=models.ForeignKey(default=1, help_text='The company that this webhook belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(help_text='The event that will trigger this webhook. E.g. lead_created, lead_updated, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(help_text='The URL that will receive the webhook payload.'),
        ),
    ]
